highlighter: pygments
markdown: redcarpet

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Alex"
      title: "null"
      archives: "active"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Alex"
      title: "null"
