# conversion
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM

# outputting
permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Alex"
      title: "null"
      archives: "active"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Alex"
      title: "null"

# variables
url: https://avanpo.github.io
